### ISSUE TITLE
yasunori apiの呼び出しをcloudflare workersのservice bindingsで呼び出す

### ISSUE THREAD

**Issue by ryoppippi** [times-yasunori/awesome-yasunori#41]
現在の実装だと、webからapiを叩くときは普通にURLを叩いているが、同じ組織のcloudflare にworkersもいるのでservice bindingsを使って呼ぶと良さそう
https://developers.cloudflare.com/workers/runtime-apis/bindings/service-bindings/

**Comment by tomoya** [comment]
あんまり CF に依存するコードは入れたくないですねー

**Comment by ryoppippi** [comment]
確かにそれはそうかもしれないですね
